# Install composer
- name: Download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer

- name: Install composer
  command: php /tmp/composer-installer --install-dir=/usr/local/bin/ --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Copy aliases
  copy:
    src: /vagrant/files/aliases
    dest: /home/vagrant/.bash_aliases
    owner: vagrant
    group: vagrant
    mode: 0644
